export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"

# export PATH="/usr/local/opt/openjdk@11/bin:$PATH"
export JAVA_HOME="/usr/local/opt/openjdk"
# export PATH="/usr/local/opt/openjdk@17/bin:$PATH"
export PATH="$JAVA_HOME/bin:$PATH"
export PATH="/usr/local/opt/mysql-client/bin:$PATH"
# export PATH="/usr/local/bin/chromedriver:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/projects/app/sonar-scanner-5.0.1.3006-macosx/bin:$PATH"
